# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghrepo" do
  name "ghrepo"
  desc "GitHub repository CLI tool"
  homepage "https://github.com/JsonLee12138/ghrepo"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghrepo"

  on_macos do
    on_intel do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_darwin_amd64.tar.gz"
      sha256 "c7aae50c2a8db72a7c759fd64203325d1b2243fa87c76b2738e54c7a4f95735b"
    end
    on_arm do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_darwin_arm64.tar.gz"
      sha256 "025dd501a000e9d4860b23ce2652513c111274a8dcab946d14850491561a12cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_linux_amd64.tar.gz"
      sha256 "55a1692db3bac4c980213c7c2d2d64f7a26a2617aea4feaa58c5ae8d61a4b0d9"
    end
    on_arm do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_linux_arm64.tar.gz"
      sha256 "b26b05c8f68fbc724c045d78bc9c135f75db8d65be85a77c2d35693cff23d65c"
    end
  end

  # No zap stanza required
end
