# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghrepo" do
  name "ghrepo"
  desc "GitHub repository CLI tool"
  homepage "https://github.com/JsonLee12138/ghrepo"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghrepo"

  on_macos do
    on_intel do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_darwin_amd64.tar.gz"
      sha256 "7613d7f31c65acdf235a2b07a605fc7bcd68e480aefa141c2fc58ec77b283d27"
    end
    on_arm do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_darwin_arm64.tar.gz"
      sha256 "f96e61270a335e7bf92fe7e27c2514c6ddd87d93681e8abdfbf3e68a0453f59a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_linux_amd64.tar.gz"
      sha256 "05e5e7f728c91aa148b9587e158e77281a429debb05fedd75167531f053e4ebe"
    end
    on_arm do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_linux_arm64.tar.gz"
      sha256 "5c8c935aafc14c354803b1b070b612ef708d7b3fea8dfd73d842b4e5094b09cb"
    end
  end

  # No zap stanza required
end
