# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghrepo" do
  name "ghrepo"
  desc "Read-only GitHub repository CLI tool"
  homepage "https://github.com/JsonLee12138/ghrepo"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghrepo"

  on_macos do
    on_intel do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_darwin_amd64.tar.gz"
      sha256 "fa9e66a51f208a926f8e5149fdaf686521ebad5cbbc9766617c3d7ce4a6a399a"
    end
    on_arm do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_darwin_arm64.tar.gz"
      sha256 "b6b00bb336942f43455ee16ca91244ccbb12c7c223f1ad03f888aba57f8da7c9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_linux_amd64.tar.gz"
      sha256 "e14edf5ddb5f95432fa459015d9288e81fcaa3b04b475f60d9c6432da25eb364"
    end
    on_arm do
      url "https://github.com/JsonLee12138/ghrepo/releases/download/v#{version}/ghrepo_#{version}_linux_arm64.tar.gz"
      sha256 "42668e67c3efee30a80130cf512c22509c72109df68ca0e31b201e70219fbacf"
    end
  end

  # No zap stanza required
end
